name: 📌 Add dependency PRs to board

permissions:
  contents: read # access to read repository's content

on:
  schedule:
    - cron: '30 5 * * *'
  pull_request:
    types: [opened, reopened, labeled]
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run mode'
        required: false
        type: boolean
        default: true

jobs:
  add-to-project:
    name: Add pull requests to project
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository
      #   id: checkout
      #   uses: actions/checkout@v7
      #   with:
      #     persist-credentials: false

      - name: Get auth token
        id: auth-token
        uses: stairwaytowonderland/actions/.github/actions/auth-token-action@v1
        with:
          # github-token: ${{ secrets.github-token }}
          app-private-key: ${{ secrets.ORG_REPO_USER_PRIVATE_KEY }}
          app-client-id: ${{ vars.ORG_REPO_USER_APP_ID }}

      - uses: ./add-to-project
        with:
          dry-run: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && github.inputs.dry-run || true }}
          project-url: https://github.com/orgs/${{ github.repository_owner }}/projects/5
          github-token: ${{ steps.auth-token.outputs.token }}
          labeled: dependencies
          repo: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && github.repository || '' }}
