name: 🔄 CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'package.json'
      - 'package-lock.json'

    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      tag:
        description: 'Existing release tag to publish (e.g. v1.2.3)'
        type: string
        default: '' # checkov:skip=CKV_GHA_7: Tag required for automated dispatch, which is used for the first tag/release
      notes-b64:
        description: 'Base64-encoded release notes (Markdown)'
        type: string
        default: '' # checkov:skip=CKV_GHA_7: Release notes required for automated dispatch, which is used for the first tag/release
      skip-tests:
        description: 'Skip running tests'
        type: boolean
        default: false

concurrency:
  group: '${{ github.repository_id }}-${{ github.ref_name }}'
  cancel-in-progress: ${{ github.event_name == 'push' }}

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

# Use PAT instead of GITHUB_TOKEN to cause semantic-release to trigger tag pipeline when tag is created.
# 'Fine-grained token' repo permissions: Contents

jobs:
  check-dist:
    name: 🏗️ Check Transpiled JavaScript
    if: github.event_name != 'push' || ! startsWith(github.ref, 'refs/tags/')
    # if: github.event_name == 'push' || ! inputs.skip-tests
    uses: ./.github/workflows/check-dist.yaml
    permissions:
      contents: read
  test-action:
    name: 🔔 Test Action
    if: github.event_name != 'push' || ! startsWith(github.ref, 'refs/tags/')
    # if: github.event_name == 'push' || ! inputs.skip-tests
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    permissions:
      contents: read
      actions: read
  release-and-publish:
    name: 📦 Release and Publish
    needs: [check-dist, test-action]
    if: |
      always() &&
      ((needs.check-dist.result == 'success' || needs.check-dist.result == 'skipped') &&
      (needs.test-action.result == 'success' || needs.test-action.result == 'skipped'))
    uses: stairwaytowonderland/.github/.github/workflows/ci.yaml@v1
    secrets: inherit
    with:
      first-release-dispatch-workflow: ci.yaml
      normalize-majorver: true
      # The following inputs are required in the workflow specified by first-release-dispatch-workflow (e.g. the ci.yaml in this case):
      tag: ${{ inputs.tag }}
      notes-b64: ${{ inputs.notes-b64 }}
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write
  # release:
  #   name: 📦 Release
  #   needs: [check-dist, test-action]
  #   uses: stairwaytowonderland/.github/.github/workflows/ci.yaml@v1
  #   secrets: inherit
  #   with:
  #     first-release-dispatch-workflow: ci.yaml
  #   permissions:
  #     actions: write
  #     contents: write
  #     issues: write
  #     pull-requests: write
  # publish:
  #   name: 📦 Publish
  #   if: github.event_name != 'push' || startsWith(github.ref, 'refs/tags/')
  #   uses: stairwaytowonderland/.github/.github/workflows/ci.yaml@v1
  #   secrets: inherit
  #   with:
  #     normalize-majorver: true
  #     # The following inputs are required in the workflow specified by first-release-dispatch-workflow (e.g. the ci.yaml in this case):
  #     tag: ${{ inputs.tag }}
  #     notes-b64: ${{ inputs.notes-b64 }}
  #   permissions:
  #     actions: write
  #     contents: write
  #     issues: write
  #     pull-requests: write
